version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 20

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 20

  - package-ecosystem: "docker"
    directory: "/build-wasm/"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 20
